### ISSUE TITLE
Preset speed

### ISSUE THREAD

**Issue by steve512** [bitfocus/companion-module-sony-visca#26]
i have a minrray ptz which supports sony visca protocoll. but somehow the preset speed function does not work. 
any known issue with that?
thanks!

**Comment by goseid** [comment]
Hi @steve512 

Its been a long time since you submitted your issue. Are you able to test if this works now? I haven't intentionally changed anything in regards to the way the module handles preset speed, but I did test it with my Sony cameras and it works on those.

One thing that is a little odd on my cameras is if you send the action to change the speed of a preset while it is in the middle of a move from one preset to another, the command is ignored. In my case I had to make sure the camera wasn't moving when setting the Preset Drive Speed then it worked as expected.

Please let us know if it works with your minrray camera.
